### ISSUE TITLE
Background broken with new update from TST

### ISSUE THREAD

**Issue by haoadoreorange** [piroor/tst-active-tab-in-collapsed-tree#10]
It seems that there's something broken with new update from TST. The background of the active tab now completely transparent thus we see both of the text overlapped.
![image](https://user-images.githubusercontent.com/22086462/122291971-f8627700-cee4-11eb-9d02-fd27269f8bae.png)

**Comment by piroor** [comment]
Which version of TST and TST Active Tab in Collapsed Tree? And what theme do you use? Sadly I couldn't see this problem on my environment. What I did is:

1. Log on to Windows 10.
2. Set the application color scheme "light".
3. Start Firefox Nightly 91.0a1 with clean profile.
4. Go to toolbar customization and choose the "System theme" as the theme.
5. Install latest development build of TST: https://github.com/piroor/treestyletab#development-builds
6. Go to TST options => Appearance => Theme => Choose "Proton".
7. Install latest development build of TST Active Tab in Collapsed Tree: https://github.com/piroor/tst-active-tab-in-collapsed-tree/actions/runs/942883954#artifacts
8. Go to TST Active Tab in Collapsed Tree options => Theme => Choose "Proton".
9. Prepare tabs as:
   ```
   + A
     + B
   ```
10. Activate the tab B.
11. Collapse the tree A.
12. Expected result: The title of B is readable.
    Actual result: The title of B is readable. Screenshot:
    ![image](https://user-images.githubusercontent.com/70062/122315528-37c8ac00-cf55-11eb-9e4c-adb3d6bae10d.png)

Report with details like this will help my debugging a lot.

**Comment by haoadoreorange** [comment]
Sorry for the lack of info.
- TST 3.8.3
- TST Active Tab 1.0.6
- FF 89.0.1

I can confirm it's working correctly on Proton theme, the behaviour I showed is only on Photon theme.

**Comment by piroor** [comment]
I still cannot see the problem on my environment with these steps:

1. Log on to Windows 10.
2. Set the application color scheme "dark".
3. Start Firefox 89.0 with clean profile.
4. Go to about:config and set Proton disabled with:
   * `browser.proton.enabled` => false
5. Go to toolbar customization and choose the "System theme" as the theme.
6. Install TST 3.8.3: https://addons.mozilla.org/firefox/addon/tree-style-tab/
7. Go to TST options => Appearance => Theme => Choose "Photon".
8. Install TST Active Tab in Collapsed Tree 1.0.6: https://addons.mozilla.org/firefox/addon/tst-active-tab-in-collapsed-tr/
9. Go to TST Active Tab in Collapsed Tree options => Theme => Choose "Photon".
10. Prepare tabs as:
    ```
    + A
      + B
    ```
11. Activate the tab B.
12. Collapse the tree A.
13. Expected result: The title of B is readable.
    Actual result: The title of B is readable. Screenshot:
    ![image](https://user-images.githubusercontent.com/70062/122543547-dabd1b00-d066-11eb-9eac-5ff3153a4e9f.png)

Do you use any theme of Firefox itself?

**Comment by haoadoreorange** [comment]
Indeed not the theme but I use some custom css for TST. I will close the issue here.

**Comment by haoadoreorange** [comment]
So indeed the thing was broken with a combination of photon/themes. Here's the little fix I made in case anyone have the same problem.
```
/* Fix TST Active Tab style */
/* With some animated themes there is a white background when you hover it, this is to streamline the background */
::part(extra-contents-by-tst-active-tab-in-collapsed-tree_piro_sakura_ne_jp tab) {
	background-color: var(--theme-colors-tab);
}

/* Same but for closebox */
::part(extra-contents-by-tst-active-tab-in-collapsed-tree_piro_sakura_ne_jp closebox) {
	background-color: var(--theme-colors-tab);
}

::part(extra-contents-by-tst-active-tab-in-collapsed-tree_piro_sakura_ne_jp closebox-icon) {
	background-color: white;
}
```
