### ISSUE TITLE
The active tab is not properly aligned at 100%

### ISSUE THREAD

**Issue by haoadoreorange** [piroor/tst-active-tab-in-collapsed-tree#11]
I've always noticed this since a long time in every version.
When set to 100% the active tab is not properly aligned with the parent tab, it is somehow higher.
Only set to 94.5% it is perfectly aligned.

This is 100%
![image](https://user-images.githubusercontent.com/22086462/122606402-66837700-d068-11eb-8a48-83ac275ffcd0.png)

This is 94.5%
![image](https://user-images.githubusercontent.com/22086462/122606431-73a06600-d068-11eb-8ba4-a04d6cfc33b1.png)

**Comment by piroor** [comment]
Thanks, the difference looks to be produced by the offset for "Photon" theme. With the commit 514a1c9 100% height should be applied as expected for "Proton" theme.

**Comment by haoadoreorange** [comment]
Thanks for the fix !
