### ISSUE TITLE
Is it Possible to Control the Horizontal size of the Active Tab?

### ISSUE THREAD

**Issue by lukasubo** [piroor/tst-active-tab-in-collapsed-tree#7]
The settings allow you to set the active tab to a %age of the full height, but not a %age of the full width, which would be useful for still being  able to read the top-level tab name.

I've been playing with the CSS, but I haven't been able to get it working - any padding I add is still opaque and covers the top-level tab anyways. Is there an easy way to do this?

**Comment by piroor** [comment]
With specifying the calculated common part name with the format `extra-contents-by-(sanitized addon id)`, you can customize styling of shadow DOM contents. Sanititing is done with a rule: replacing all unsafe characters except alphabets, numbers, hyphen and underscore with `_`. For example, if the id is `tst-active-tab-in-collapsed-tree@piro.sakura.ne.jp`, unsafe characters `@` and `.` are replaced then the result becomes `extra-contents-by-tst-active-tab-in-collapsed-tree_piro_sakura_ne_jp`. Please read this:
https://github.com/piroor/treestyletab/wiki/Extra-Tab-Contents-API#styling-with-custom-user-styles

regards,

**Comment by piroor** [comment]
You can do that with a custom user style in TST options.
https://github.com/piroor/treestyletab/wiki/Extra-Tab-Contents-API#styling-with-custom-user-styles

For example:

```css
::part(extra-contents-by-tst-active-tab-in-collapsed-tree_piro_sakura_ne_jp tab-container) {
  left: 2em;
}
```

**Comment by lukasubo** [comment]
Thanks! That had exactly the effect I was looking for.

![image](https://user-images.githubusercontent.com/5761515/115594163-6999fb00-a2a3-11eb-978a-04c723473037.png)

```
::part(extra-contents-by-tst-active-tab-in-collapsed-tree_piro_sakura_ne_jp tab-container) {
  left: 40%;
}
```
